exports.seed = async function (knex) {
  // Deletes ALL existing entries
  return knex("shoesInfo")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("shoesInfo").insert([
        {
          id: 1,
          name:
            "Converse Chuck Taylor All-Star 70s Hi Fear Of God Black Natural",
          color: "BLACK",
          type: "Sneaker",
          size: "US_8",
          year_bounght: "2017",
          where_to_bought: "KOREA Soul",
        },
        {
          id: 2,
          name: " CHUCK TAYLOR 1970S OX FLAMES WHITE, ENAMEL RED & MANDARIN",
          color: "WHITE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2010",
          where_to_bought: "USA LA",
        },
        {
          id: 3,
          name: " CHUCK TAYLOR 1970S ",
          color: "RED",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2009",
          where_to_bought: "USA",
        },
        {
          id: 4,
          name: " CHUCK TAYLOR 1970S",
          color: "GREEN",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2011",
          where_to_bought: "USA",
        },
        {
          id: 5,
          name: " CONS One Start Pro",
          color: "CREAM",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2009",
          where_to_bought: "USA",
        },
        {
          id: 6,
          name: " CHUCK TAYLOR 1970S",
          color: "BLUE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2008",
          where_to_bought: "KOREA",
        },
        {
          id: 7,
          name: " CHUCK TAYLOR 1970S",
          color: "WHITE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2008",
          where_to_bought: "KOREA",
        },
        {
          id: 8,
          name: " CHUCK TAYLOR 1970S",
          color: "BLACK",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2011",
          where_to_bought: "USA",
        },
        {
          id: 9,
          name: " CHUCK TAYLOR 1970S",
          color: "CREAM",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2007",
          where_to_bought: "KOREA",
        },
        {
          id: 10,
          name: " ALL STAR",
          color: "WHITE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2008",
          where_to_bought: "JAPAN",
        },
        {
          id: 11,
          name: " ALL STAR",
          color: "WHITE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2006",
          where_to_bought: "JAPAN",
        },
        {
          id: 12,
          name: " CHUCK TAYLOR 1970S",
          color: "BLUE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2012",
          where_to_bought: "USA",
        },
        {
          id: 13,
          name: " CHUCK TAYLOR 1970S",
          color: "BLACK",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2008",
          where_to_bought: "AUS",
        },
        {
          id: 14,
          name: " CHUCK TAYLOR 1970S",
          color: "PINK",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2009",
          where_to_bought: "AUS",
        },
        {
          id: 15,
          name: " CHUCK TAYLOR 1970S",
          color: "BLACk",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2012",
          where_to_bought: "AUS",
        },
        {
          id: 16,
          name: " CHUCK TAYLOR 1970S",
          color: "WHITE",
          type: "Sneaker",
          size: "US_7",
          year_bounght: "2008",
          where_to_bought: "KOREA",
        },
      ]);
    });
};
